import { useState, useCallback } from 'react';
import { Sidebar, ChatArea, LandingPage } from './components';
import type { Chat, Dataset } from './types';
import { DATASETS, generateId } from './types';
import './App.css';

function App() {
  const [view, setView] = useState<'landing' | 'app'>('landing');
  const [chats, setChats] = useState<Chat[]>([]);
  const [selectedChatId, setSelectedChatId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const selectedChat = chats.find((chat) => chat.id === selectedChatId) || null;

  const handleNewChat = useCallback((dataset: Dataset) => {
    const newChat: Chat = {
      id: generateId(),
      title: `New ${dataset.name} Chat`,
      dataset,
      messages: [],
      createdAt: new Date(),
    };
    setChats((prev) => [newChat, ...prev]);
    setSelectedChatId(newChat.id);
  }, []);

  const handleSelectChat = useCallback((chatId: string) => {
    setSelectedChatId(chatId);
  }, []);

  const handleDeleteChat = useCallback((chatId: string) => {
    setChats((prev) => prev.filter((chat) => chat.id !== chatId));
    if (selectedChatId === chatId) {
      setSelectedChatId(null);
    }
  }, [selectedChatId]);

  const handleSendMessage = useCallback((content: string) => {
    if (!selectedChatId) return;

    const userMessage = {
      id: generateId(),
      role: 'user' as const,
      content,
      timestamp: new Date(),
    };

    setChats((prev) =>
      prev.map((chat) =>
        chat.id === selectedChatId
          ? {
              ...chat,
              title: chat.messages.length === 0 ? content.slice(0, 30) + '...' : chat.title,
              messages: [...chat.messages, userMessage],
            }
          : chat
      )
    );

    setIsLoading(true);
    setTimeout(() => {
      const assistantMessage = {
        id: generateId(),
        role: 'assistant' as const,
        content: `This is a placeholder response. In a real application, this would be generated by an AI model querying the "${selectedChat?.dataset.name}" dataset.`,
        timestamp: new Date(),
      };

      setChats((prev) =>
        prev.map((chat) =>
          chat.id === selectedChatId
            ? { ...chat, messages: [...chat.messages, assistantMessage] }
            : chat
        )
      );
      setIsLoading(false);
    }, 1500);
  }, [selectedChatId, selectedChat?.dataset.name]);

  const handleDatasetChange = useCallback((newDataset: Dataset) => {
    if (!selectedChatId) return;
    setChats((prev) =>
      prev.map((chat) =>
        chat.id === selectedChatId ? { ...chat, dataset: newDataset } : chat
      )
    );
  }, [selectedChatId]);

  if (view === 'landing') {
    return <LandingPage onLaunch={() => setView('app')} />;
  }

  return (
    <div className="app">
      <Sidebar
        chats={chats}
        selectedChatId={selectedChatId}
        onSelectChat={handleSelectChat}
        onNewChat={handleNewChat}
        onDeleteChat={handleDeleteChat}
        datasets={DATASETS}
      />
      <main className="main-content">
        <ChatArea
          chat={selectedChat}
          onSendMessage={handleSendMessage}
          onDatasetChange={handleDatasetChange}
          isLoading={isLoading}
        />
      </main>
    </div>
  );
}

export default App;
